add_newline = true

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$cmd_duration\
$character
"""
[os]
disabled = false
style = "bold blue"

[os.symbols]
Arch = "󰣇 "

[username]
show_always = false
style_user = "bold white"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "bold dimmed white"
format = "[@$hostname]($style) "

[directory]
style = "bold cyan"
home_symbol = "󰋜 "
read_only = " 󰌾"
read_only_style = "red"
truncation_length = 4
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "
"Desktop" = "󰇄 "
"Netzlaufwerke" = "󰛳 "

[git_branch]
symbol = " "
style = "bold magenta"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "[$all_status$ahead_behind]($style) "

[cmd_duration]
min_time = 1000
show_milliseconds = false
style = "bold yellow"
format = "took [$duration]($style) "

[python]
symbol = " "
style = "bold yellow"
format = "via [$symbol$version]($style) "

[nodejs]
symbol = " "
style = "bold green"
format = "via [$symbol$version]($style) "

[rust]
symbol = " "
style = "bold red"
format = "via [$symbol$version]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "bold dimmed white"
format = "[$time]($style) "

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
